# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lL_9ABZV0a00fZSGQvE_4jfS2Jomg4nl
"""

"""
Генерация синтетических данных A/B-эксперимента.

Сценарий: тестируем новую кнопку.
Группа A — контроль, конверсия 10.0%
Группа B — тест, конверсия 11.2% (реальный аплифт +1.2 п.п.)

Результат: data/ab_test.csv с колонками
    user_id, group, converted, revenue
"""

import os
import numpy as np
import pandas as pd


# 1. Воспроизводимость

np.random.seed(42)

# 2. Параметры эксперимента

N_USERS = 60000              # всего пользователей
SHARE_B = 0.5                # доля пользователей в группе B

P_A = 0.100                  # конверсия в группе A (контроль)
P_B = 0.112                  # конверсия в группе B (тест, +1.2 п.п.)

# Распределение выручки от одного конвертированного пользователя.
# Логнормальное распределение — типично для денежных величин:
# основная масса небольших чеков + «тяжёлый хвост» крупных покупок.
REVENUE_MEAN = 1500.0        # средний чек, руб.
REVENUE_SIGMA = 0.6          # разброс (в лог-шкале)


# 3. Формируем пользователей и распределяем по группам

user_ids = np.arange(1, N_USERS + 1)

# Случайно (с заданной вероятностью) относим каждого пользователя
# в группу B, остальные попадают в A.
is_b = np.random.rand(N_USERS) < SHARE_B

groups = np.where(is_b, "B", "A")


# 4. Моделируем конверсию

# Для каждого пользователя бросаем «монетку» с вероятностью,
# зависящей от его группы.
p_convert = np.where(is_b, P_B, P_A)
converted = (np.random.rand(N_USERS) < p_convert).astype(int)

# 5. Моделируем выручку

# Выручка есть только у конвертированных пользователей.
# Логнормальное распределение: revenue = exp(mu + sigma * z),
# где mu подобран так, чтобы среднее равнялось REVENUE_MEAN.
mu = np.log(REVENUE_MEAN) - 0.5 * REVENUE_SIGMA ** 2

revenue = np.zeros(N_USERS)
n_converted = converted.sum()
revenue[converted == 1] = np.random.lognormal(
    mean=mu,
    sigma=REVENUE_SIGMA,
    size=n_converted,
).round(2)

# 6. Собираем DataFrame

df = pd.DataFrame({
    "user_id": user_ids,
    "group": groups,
    "converted": converted,
    "revenue": revenue,
})


# 7. Сохраняем в CSV

os.makedirs("data", exist_ok=True)
df.to_csv("data/ab_test.csv", index=False)


# 8. Краткая сводка по сгенерированным данным
print("Сгенерировано пользователей:", len(df))
print()
summary = (
    df.groupby("group")
      .agg(
          users=("user_id", "count"),
          conversions=("converted", "sum"),
          conversion_rate=("converted", "mean"),
          total_revenue=("revenue", "sum"),
          arpu=("revenue", "mean"),
      )
      .round(4)
)
print(summary)
print()

lift = (
    summary.loc["B", "conversion_rate"]
    - summary.loc["A", "conversion_rate"]
)
print(f"Абсолютный аплифт конверсии (B - A): {lift:+.4f}")
print(f"Относительный аплифт: {lift / summary.loc['A', 'conversion_rate']:+.2%}")
print()
print("Файл сохранён: data/ab_test.csv")